steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-ride-names', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/go-ride-names']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'go-ride-names'
      - '--image'
      - 'gcr.io/$PROJECT_ID/go-ride-names'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'STRAVA_CLIENT_ID=STRAVA_CLIENT_ID:latest,STRAVA_CLIENT_SECRET=STRAVA_CLIENT_SECRET:latest'
      - '--set-env-vars'
      - >-
        BASE_URL=https://go-ride-names-se2bdxecnq-uc.a.run.app,
        OAUTH_REDIRECT_URI=https://go-ride-names-se2bdxecnq-uc.a.run.app/callback,
        WEBHOOK_VERIFY_TOKEN=strava-webhook-verify-token-123,
        REDIS_URL=redis://10.0.0.3:6379

images:
  - 'gcr.io/$PROJECT_ID/go-ride-names' 