steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/zoatleta', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zoatleta']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'zoatleta'
      - '--image'
      - 'gcr.io/$PROJECT_ID/zoatleta'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'zoatleta-storage@zoatleta.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - >-
        STRAVA_CLIENT_ID=STRAVA_CLIENT_ID:latest,
        STRAVA_CLIENT_SECRET=STRAVA_CLIENT_SECRET:latest
      - '--set-env-vars'
      - >-
        BASE_URL=https://zoatleta.tech,
        OAUTH_REDIRECT_URI=https://zoatleta.tech/callback,
        WEBHOOK_VERIFY_TOKEN=strava-webhook-verify-token-123,
        GCS_BUCKET_NAME=zoatleta-storage

images:
  - 'gcr.io/$PROJECT_ID/zoatleta'

options:
  logging: CLOUD_LOGGING_ONLY 