package service

import "strings"

// Define activity types based on Strava sport_type
const (
	// Basic types
	Run            = "Run"
	Ride           = "Ride"
	Swim           = "Swim"
	Walk           = "Walk"
	Workout        = "Workout"
	WeightTraining = "WeightTraining"
	Yoga           = "Yoga"

	// Additional types
	Hike             = "Hike"
	TrailRun         = "TrailRun"
	VirtualRide      = "VirtualRide"
	VirtualRun       = "VirtualRun"
	Elliptical       = "Elliptical"
	StairStepper     = "StairStepper"
	Crossfit         = "Crossfit"
	Pilates          = "Pilates"
	Skateboard       = "Skateboard"
	Surf             = "Surf"
	Soccer           = "Soccer"
	Squash           = "Squash"
	MountainBikeRide = "MountainBikeRide"
	Canoeing         = "Canoeing"

	Default = "Default"
)

// Update the activity type detection
func getActivityType(activityName string, sportType string) string {
	// First try to match by sport_type if available
	switch sportType {
	case Run, Ride, Swim, Walk, Workout, WeightTraining, Yoga,
		Hike, TrailRun, VirtualRide, VirtualRun, Elliptical,
		StairStepper, Crossfit, Pilates, Skateboard, Surf,
		Soccer, Squash, MountainBikeRide, Canoeing:
		return sportType
	}

	// Fallback to name-based detection for backward compatibility
	switch {
	case strings.Contains(activityName, "Run"):
		return Run
	case strings.Contains(activityName, "Ride"):
		return Ride
	case strings.Contains(activityName, "Swim"):
		return Swim
	case strings.Contains(activityName, "Walk"):
		return Walk
	case strings.Contains(activityName, "Weight Training"):
		return WeightTraining
	case strings.Contains(activityName, "Yoga"):
		return Yoga
	default:
		return Default
	}
}

var activityJokes = map[string][]string{
	Run: {
		"🏃‍♂️ 'Minha corrida é como meu código: cheia de loops infinitos e erros inesperados.'",
		"👟 'Tentei correr como no Counter-Strike, mas esqueci que na vida real não existe bunny hop.'",
		"🏃‍♀️ 'Meu pace é tão lento que o lag do servidor pensou que eu tinha desconectado.'",
		"🕹️ 'Correr é como compilar um programa: demora, dá erro, mas eventualmente funciona.'",
		"🎮 'Se houvesse um modo fácil na vida real, corrida seria um quicksave antes de cada ladeira.'",
		"⚔️ 'Eu corro com a mesma estratégia de um bárbaro de D&D: tudo na força, zero na destreza.'",
		"🏃‍♂️ 'A diferença entre correr e programar? No código, você pode debugar; na corrida, só sofre.'",
		"🖱️ 'Correndo me sinto no Dota: muita ação, mas no final meu time (meu corpo) me deixa na mão.'",
		"🎲 'Teste de resistência na corrida? Rolei 1 crítico e tropecei no próprio cadarço.'",
		"🏃‍♀️ 'Corrida longa é como um RPG de turno: decisões lentas e dor a cada movimento.'",
		"🔧 'Preciso de um script em Python para automatizar minhas pernas. Esse loop manual está ineficiente.'",
		"🌌 'Correr é como jogar Skyrim: você começa empolgado, mas logo quer fast travel até o final.'",
		"🎮 'Eu corro como um bot do CS: reto para a parede, sem desviar dos obstáculos.'",
		"🧙‍♂️ 'Se fosse um mago, eu usaria teleport. Mas não, sou só um humano com pouca estamina.'",
		"🏃‍♂️ 'Correr é o debug da vida: a cada erro você fica mais perto de uma solução (ou da desistência).'",
		"🛡️ 'Na corrida, sou um tanque de RPG: movo devagar, mas aguento bastante dano emocional.'",
		"🎲 'Rolei iniciativa para correr, mas o mestre deu uma ladeira de desvantagem.'",
		"🏃‍♂️ '404: Endorfina não encontrada'... e o pace foi pro espaço.",
		"🖥️ 'Corrida em loop infinito'... quando me perco no parque sem GPS.",
		"💾 'Ctrl+C, Ctrl+V'... do meu treino de 5k pra todo santo sábado.",
		"⚙️ 'Compilando PR'... mas o sistema travou no km 3.",
		"🌐 'Servidor não responde'... é como me sinto depois de uma subida de 1km.",
		"🛠️ 'Stack Overflow'... quando faço mais treinos do que consigo recuperar.",
		"🔒 'Access denied'... porque o joelho não deixou eu correr hoje.",
		"🔄 'Deploy no asfalto'... e o rollback é sempre uma dor na panturrilha.",
		"🧩 'NullPointerException'... é o treino sem o tênis certo.",
		"📡 'Ping alto'... quando o batimento chega a 180 no sprint.",
		"🌀 'Infinite loop'... minha sensação no treino de tiro 10x400m.",
		"🚦 'Debugando o pace'... porque meu relógio nunca acerta.",
		"💻 'Hello, world!'... ou 'olá, asfalto' no meu primeiro 10k.",
		"🔋 'Battery low'... e ainda faltam 3km pra casa.",
		"🐛 'Bug na planilha'... porque o longão parece impossível.",
		"📈 'O algoritmo do pace'... nunca inclui o vento contra.",
		"⚠️ 'Erro 500'... quando tento correr depois de um treino de pernas.",
		"🔐 'Token expirado'... minha energia no km 8 do longão.",
		"📊 'KPI: PR semanal'... mas o servidor (eu) está fora do ar.",
		"📎 'Quer ajuda para alongar?'... perguntou o Clippy no pós-corrida.",
		"⏳ 'Tempo de execução elevado'... quando corro depois de uma noite mal dormida.",
		"🔗 'Link quebrado'... é o que parece meu tornozelo depois de uma trilha.",
		"💨 'Cache limpo'... ou seja, treino em jejum de manhã cedo.",
		"📡 'DNS não resolvido'... porque o GPS ficou doido na prova.",
		"🖱️ 'Double click'... no lap acidental e bagunçou meu treino.",
		"🏁 'System.out.println('Terminei a prova!'')'... e tá tudo logado no Strava.",
		"📲 'Push feito'... mas o pull (recovery) ficou pra amanhã.",
		"💻 'Kernel panic'... quando dá cãibra no meio do treino.",
		"🚀 'Deploy feito com sucesso'... e criei meu PR no 5k!",
		"🕹️ 'Game over'... na subida, mas reinicio no plano.",
		"🖱️ 'Meu pace é tão ruim que no LoL seria considerado feeding.'",
		"🎮 'Correr na chuva me faz sentir no GTA: escorregando e batendo em tudo sem controle.'",
		"🏃‍♀️ 'Se corrida fosse multiplayer, eu seria o cara carregado na partida.'",
		"🕹️ 'Correr é como grindar XP: chato, repetitivo, mas eventualmente você level up.'",
		"🔍 'A diferença entre programação e corrida? Na primeira eu só travo, na segunda eu travo e caio.'",
		"🏃‍♂️ 'Depois de uma corrida, minha stack overflow é muscular.'",
		"⚔️ 'Meu DM disse que correr era bom para stamina. Ele esqueceu de me avisar sobre a dor eterna.'",
		"🎮 'Correr na esteira é como o loading screen: a sensação de ir a lugar nenhum.'",
		"🧙‍♂️ 'Tentei correr como um rogue. Esqueci que não tenho stealth nem agilidade.'",
		"🏃‍♀️ 'Na corrida, meu pace é tão lento que pareço um NPC de fetch quest.'",
		"🎲 'Se corrida fosse uma rolagem de dados, minha constituição seria -2.'",
		"🕹️ 'Correr é como no Dota: você tenta fugir, mas sempre tem uma torre (colina) para te acabar.'",
		"⚔️ 'Correr de manhã é uma side quest: muita dificuldade por pouca recompensa.'",
		"🏃‍♂️ 'Me inscrevi para uma corrida. Parecia um evento bônus, mas virou um boss fight.'",
		"🎮 'Meu pace é tipo conexão dial-up: lento, instável e com muitas quedas.'",
		"🖱️ 'Corrida é um bug no meu sistema: pernas não conectam com motivação.'",
		"🏃‍♀️ 'Tentei correr full stack, mas fiquei preso no front-end: as pernas.'",
		"🎮 'Se correr é um jogo, a minha dificuldade está setada em pesadelo.'",
		"🌌 'Corrida me lembra No Man's Sky: interminável e cheia de frustrações.'",
		"⚔️ 'Se fosse uma quest, correr seria hardcore mode: 1 erro e você sente por uma semana.'",
		"🏃‍♂️ 'Meu pace é como um servidor sem cache: lento e constante.'",
		"🖱️ 'Corro como um mago com lag: muito preparo, pouco movimento.'",
		"🎮 'Corrida é como farmar em MMORPG: lenta e dolorosa, mas alguém diz que vale a pena.'",
	},
	Ride: {
		"🚴‍♀️ Subindo a serra, pensei: ‘Stairway to Heaven’, ou direto pro inferno das coxas?",
		"🚴‍♀️ Depois de 70km na trilha, meu corpo pediu arrego e cantou ‘I’m Still Standing’.",
		"🎸 No downhill insano, senti o espírito de ‘Free Bird’ tomando conta.",
		"💨 A ventania me empurrando na reta parecia o refrão de ‘Go Your Own Way’.",
		"🌌 Madrugada gelada no pedal... foi tipo ‘Cold as Ice’, mas sem glam rock.",
		"🔥 No sprint final, só dava pra pensar: sou o ‘Eye of the Tiger’ dessa trilha!",
		"🎶 Subida interminável? Minha playlist mental tocou ‘Climb’ até o topo.",
		"💥 No pedal urbano, desviando dos carros, virei ‘Bullet with Butterfly Wings’.",
		"🌬️ Pedalar com vento de frente é quase ouvir ‘Wind of Change’ contra minha vontade.",
		"🌈 Arco-íris na trilha e um silêncio inspirador... senti ‘What a Feeling’!",
		"🚴‍♂️ Acelerar no pelotão é sempre uma homenagem a ‘Break on Through’ do meu limite.",
		"🎤 No meio da subida impossível, gritei mentalmente: ‘Don’t Let Me Be Misunderstood!’",
		"🌌 Pedal noturno na trilha silenciosa? Só eu e ‘Moonlight Drive’ da imaginação.",
		"⚡ Depois de pegar a reta perfeita, me senti em ‘Born to Run’, mas de bike.",
		"🌄 Aquele trecho longo e vazio parecia o tema perfeito de ‘Wherever I May Roam’.",
		"🎸 Com um tombo na trilha, só pensei: ‘Should I Stay or Should I Go?’ agora?",
		"🎶 Sabe aquele vento contra? Parece que o ‘Highway to Hell’ foi asfaltado pra bikes.",
		"🤘 Hoje o treino foi tão insano que merecia trilha sonora do ‘Master of Puppets’.",
		"🚴‍♂️ No meio da trilha, só escutei o eco: ‘Knockin’ on Heaven’s Door’... era minha panturrilha gritando.",
		"🔥 Pedalar no sol das 14h deveria se chamar ‘Blaze of Glory’.",
		"🌪️ Descendo a serra a 60km/h, pensei: é agora que viro um ‘Rider on the Storm’.",
		"🎸 No último sprint do treino, senti ‘The Final Countdown’ tocar na alma.",
		"⚡ Depois de 40km, não sei se era cansaço ou só ‘Thunderstruck’ nas pernas.",
		"🌈 Na trilha molhada, derrapei tanto que parecia estar cantando ‘Have You Ever Seen the Rain?’.",
		"💀 A subida era impossível... ‘Nothing Else Matters’, só sobreviver.",
		"🌬️ Com o vento a favor, eu era o ‘Highway Star’ do pelotão!",
		"🎵 A cada subida, mais perto do meu ‘Stairway to Heaven’ pessoal.",
		"🚴‍♂️ Perdi o pelotão na descida... só ouvi ‘Another One Bites the Dust’ tocando na mente.",
		"🔥 O calor era tanto que meu pedal virou uma performance de ‘Light My Fire’.",
		"🌌 Subindo sozinho na madrugada... parecia o início de ‘Bohemian Rhapsody’.",
		"🤘 No último quilômetro, as pernas disseram: ‘Don’t Stop Me Now!’.",
		"🎤 Meu treinador sempre fala: ‘You Can’t Always Get What You Want’... principalmente nas subidas.",
		"🎶 Um PR tão incrível no Strava que até o ‘Sweet Child O’ Mine’ vibrou comigo.",
		"🌪️ Quando a chuva começou na trilha, virou ‘November Rain’ ao vivo.",
		"🚴‍♀️ Pedal noturno, com lua cheia, me senti ‘Comfortably Numb’ com o silêncio.",
		"💨 Sprint final, suor escorrendo... parecia um videoclipe de ‘Born to Be Wild’.",
		"🛠️ Consertar corrente na trilha? É quase como cantar ‘Fix You’ no desespero.",
		"🚲 Pneu furado de novo? Isso é o verdadeiro ‘Dust in the Wind’.",
		"🏔️ Subida longa? Respira e pensa: ‘Livin’ on a Prayer’.",
		"🎸 Descer na trilha com pedras? Senti o espírito de ‘Rock and Roll’.",
		"⚡ Quando o pelotão acelera, só dá pra ouvir ‘Thunderstruck’ na mente.",
		"🚴‍♂️ Se o pedal fosse uma música, hoje seria ‘Welcome to the Jungle’ na lama.",
		"🔥 Subida com 15% de inclinação é o meu ‘Highway to Hell’ particular.",
		"💀 Sabe aquele tombo de bike? Parece um cover ao vivo de ‘Knockin’ on Heaven’s Door’.",
		"🌄 No topo da serra, só dá pra pensar: isso é ‘A Whole Lotta Love’ pelo pedal.",
		"🎵 Pedalar no asfalto perfeito é como tocar ‘Smoke on the Water’ pela primeira vez.",
		"🎶 Chegar em casa depois de um pedal épico? ‘Sweet Home Alabama’, sempre.",
		"🌙 Pedalar à noite com luz de lua cheia? Momento ‘Shine On You Crazy Diamond’ garantido.",
		"🚴‍♀️ Tentando seguir o pelotão e falhando... história de ‘I Still Haven’t Found What I’m Looking For’.",
		"🎤 Hoje a trilha sonora do pedal foi ‘Take It Easy’, mas minhas pernas discordaram.",
		"💡 Quando você acha que acabou e tem outra subida... ‘Another Brick in the Wall’.",
		"🏞️ Perdi o GPS no pedal... agora é ‘Where the Streets Have No Name’ na prática.",
		"🔥 Subida tão intensa que só dava pra gritar ‘Let It Burn!’.",
		"🌈 Pedal de fim de tarde com arco-íris no horizonte? ‘Over the Rainbow’, literalmente.",
		"🎶 Quando o vento está perfeito e o dia lindo: ‘What a Wonderful World’ sobre duas rodas.",
		"🏞️ 'Country Roads'... e o cascalho me testando a cada curva.",
		"🚲 'Every Breath You Take'... é controlado na subida sem fim.",
		"🕺 'Stayin’ Alive'... depois de quase ser atropelado pelo carro na curva.",
		"🔥 'Ring of Fire'... é o que sinto nas coxas depois do pedal.",
		"🌅 'Under the Bridge'... mas só se o caminho tiver um bom plano.",
		"✨ 'Shiny Happy People'... no pedal de fim de semana com os amigos.",
		"🌞 Subir a serra ao amanhecer é a definição de ‘Sol de Primavera’ na bike.",
		"🚲 No pedal da tarde, a descida rápida foi embalada por ‘Lanterna dos Afogados’.",
		"🌌 Pedalar sob as estrelas é viver ‘O Mundo é um Moinho’, uma pedalada por vez.",
		"💨 Na ventania da trilha, pensei: hoje virei ‘O Vento’ com rodas.",
		"🔥 Com o sol no rosto e cansaço no corpo, o treino foi ‘Como Uma Onda’.",
		"🎶 Na longa reta, só eu, minha bike e ‘Caminhos do Coração’ do pedal.",
		"🏔️ No meio da subida, comecei a cantar mentalmente ‘Além do Horizonte’.",
		"🚴‍♂️ Sprint final no asfalto? Só ouvia ‘Pro Dia Nascer Feliz’ na cabeça.",
		"🌧️ Quando a chuva começou, pensei: é o meu momento ‘Tempo Perdido’ na trilha.",
		"🎤 Pedalando no escuro, virei protagonista de ‘Noite do Prazer’ versão ciclista.",
		"🚲 No downhill de cascalho, me senti desafiando o ‘Cavaleiro Andante’ do pedal.",
		"🌊 Pedal beirando o mar? Parecia tema de ‘Chega de Saudade’ ao vivo.",
		"⚡ Quando o pelotão acelera, só dá pra seguir a energia de ‘Do Seu Lado’.",
		"🎸 Na trilha de barro, com todo mundo sujo, era a vibe de ‘Até Quando Esperar’.",
		"🌌 Fechando o treino com céu estrelado... senti ‘Mais Uma Vez’ o porquê de amar pedalar.",
		"🚴‍♂️ O vento no rosto, só de bike - Chico César no treino regenerativo",
	},
	Swim: {
		"🏊‍♂️ 'Continue a nadar, continue a nadar...' - Procurando Nemo, meu mantra na série de crawl.",
		"💪 'Sou o Aquaman da piscina: poderoso até que alguém ligue o filtro.'",
		"🏋️‍♀️ 'Nadar é como Titanic: começa tranquilo, mas no final, você afunda.",
		"🦾 'Eu sou a Pequena Sereia da piscina, só que troquei o canto pelas braçadas.",
		"🏊‍♂️ *Treinar natação é como Tubarão: 'A dor está sempre à espreita.'",
		"💥 *'Nadar borboleta é tipo Moana: 'O mar te chama, mas a correnteza te segura.'",
		"🏃‍♂️ *A piscina é meu Náufrago: 'Wilson é minha touca, sempre junto.'",
		"🦵 *Nado costas é meu 'Piratas do Caribe': tentando manter o tesouro (fôlego).",
		"💪 'É um pássaro? Um avião? Não, sou eu tentando nadar crawl sem beber água.'",
		"🏊‍♀️ *Cada virada na borda é como Life of Pi: 'A luta pela sobrevivência começa.'",
		"🏊‍♂️ 'Cem anos de solidão'... ou 100 metros de nado borboleta sem respirar.",
		"🐳 'Moby Dick'... foi o nome que dei para o cara que nada golfinho mais rápido que eu.",
		"🌊 'O velho e o mar'... ou eu tentando fazer crawl com uma perna só.",
		"🤿 '20 mil braçadas submarinas'... porque esqueceram de me avisar que era dia de treino leve.",
		"💦 'Água para elefantes'... ou para mim, depois de nadar peito por 500m.",
		"🚪 'A piscina secreta'... que é como chamo aquela raia livre no horário de pico.",
		"🐠 'Peixe grande e suas histórias'... ou o cara da academia que diz que faz 50m em 10s.",
		"🦈 'Tubarão'... é assim que me sinto quando sou o único usando palmar na raia.",
		"🏝️ 'Robinson Crusoé'... ou o nadador perdido tentando entender o ritmo do treino.",
		"⛅ 'Cem dias entre céu e mar'... ou cem metros de nado costas errando a contagem.",
		"📖 'Dom Quixote'... lutando contra moinhos ou contra a resistência da água?",
		"🐙 'O chamado do mar'... ou como eu explico meu amor por séries de 400m.",
		"📅 'A insustentável leveza do ser'... quando o treino da semana é só técnica.",
		"🐬 'A metamorfose'... é como eu chamo minha tentativa de nadar golfinho.",
		"🔥 'Sob o sol da Toscana'... ou sob o sol do clube, esquecendo do protetor solar.",
		"🏞️ 'O morro dos ventos uivantes'... ou o dia que nadei contra a corrente.",
		"🕳️ 'O buraco da fechadura'... é como parece minha respiração no crawl rápido.",
		"🖋️ 'Memórias de um nadador'... que nunca aprendeu a virar na borda direito.",
		"👻 'O fantasma da piscina'... aquele que deixa todas as raias molhadas no chão.",
		"🐡 'A vida secreta dos peixes'... ou os treinos que ninguém entende na planilha.",
		"🏊‍♀️ 'O que o mar te deu, o treino te tira.' - Filosofia de Moana em dias ruins.",
		"💪 *Cada treino na piscina é como Tubarão: 'Só quero sair vivo no final.'",
		"🏋️‍♂️ *Nadar costas é 'A Forma da Água': estiloso, mas só se você souber o truque.",
		"💦 *Minha resistência na piscina é 'Aquaman': puro marketing, mas sem superpoderes.",
		"🏊‍♂️ 'A piscina tem 25 metros, mas parece o Triângulo das Bermudas.'",
		"🦾 *Nadar é como Moana: 'Você quer atravessar o oceano, mas ele sempre vence.'",
		"💪 *Borboleta é meu Titanic: 'A segunda série sempre afunda.'",
		"🏋️‍♂️ *Cada virada na borda é como Náufrago: 'Você sente que perdeu tudo, menos a touca.'",
		"💦 *Treinar nado costas é meu Pequena Sereia: 'Sempre querendo ar, mas só vejo água.'",
		"🏊‍♀️ 'Eu sou Groot!' - Eu, na borda, tentando explicar o cansaço pro treinador.",
	},
	WeightTraining: {
		"💪 Um supino para todos governar, um agachamento para achá-los, um levantamento terra para a todos trazer e na hipertrofia prendê-los.",
		"🏋️‍♂️ Você não fala sobre o clube da luta, mas todo mundo sabe quando você bate PR no deadlift.",
		"🦵 Expecto Patronum! Porque depois do treino de perna só um feitiço me salva.",
		"🏋️‍♂️ 'Você não vai passar!'... disse o agachamento com 200kg nas costas.",
		"🍗 'Me chama de Rocky Balboa, porque meu pré-treino foi só frango e ovos crus.'",
		"🎯 'May the PRs be ever in your favor'... mas o coach já sabe que vai dar ruim.",
		"🔥 'Eu sou o rei do mundo!'... até lembrar que esqueci o terra no meu treino.",
		"🤖 'Hasta la vista, baby'... e o posterior nunca mais foi o mesmo depois do RDL.",
		"🌌 'Que a força esteja com você'... porque com os glúteos não está.",
		"🐍 'Why did it have to be squats?'... disse o Indiana Jones dos joelhos fracos.",
		"🦾 'Eu sou inevitável'... como o pump de tríceps na academia.",
		"🎩 'Seja gentil, rebobine a barra'... e o coach manda eu aquecer com 100kg.",
		"🏰 'Espelho, espelho meu, quem tem o PR mais bonito que o meu?'",
		"🦁 'Hakuna Matata!'... até eu tentar fazer clean e o ombro reclamar.",
		"🪓 'Aqui é Johnny!'... entrando no treino de pernas como se não houvesse amanhã.",
		"🍿 'You can't handle the pump!'... mas o espelho tá curtindo.",
		"📖 'Era uma vez um PR...' e ele viveu feliz até a próxima semana.",
		"🚪 'Knock, knock'... quem é? É o deadlift, pronto pra me destruir.",
		"🏄‍♂️ 'Eu sou o escolhido!'... mas só porque ninguém quer fazer o burpee hoje.",
		"🎥 'Lights, camera, deadlift!'... e as costas pedem corte de cena.",
		"🦸‍♀️ 'Com grandes PRs vêm grandes responsabilidades'... tipo alongar depois.",
		"🤡 'Por que tão sério?'... só porque eu errei a pegada e quase voei.",
		"🎶 'Let it go, let it go!'... disse minha lombar na última série.",
		"🌪️ 'Depois da tempestade vem o pump'... e um joelho inchado, às vezes.",
		"🕶️ 'É o Matrix ou eu realmente desviei desse kettlebell voador?'",
		"🎃 'Eu vejo PRs mortos'... principalmente no dia de regenerativo.",
		"💀 'Diga olá ao meu pequeno amigo!'... o kettlebell de 50kg que me derrubou.",
		"🌈 'There's no place like the rack'... mas parece que todo mundo concorda, porque nunca está livre.",
		"🏋️‍♀️ Central Perk? Não, é Central PR: o lugar onde Ross nunca perde as pernas.",
		"💪 *No pain, no gain. Ou, como diria Gandalf: 'You shall not PASS... sem uma boa série de agachamentos!'",
		"🏃‍♂️ Corrida? Isso é muito 'Parkour!', disse Michael Scott enquanto fugia do treino de pernas.",
		"💥 Na academia, eu sou inevitável, igual ao Thanos no leg press.",
		"🦾 Série de bíceps: 'I'll be back.' - Arnold (e você no espelho da academia).",
		"🥵 Treinar com calor é tipo 'Dracarys!' no bíceps. Só falta o dragão do Khaleesi pra me ajudar a respirar.",
		"💪 *Treinamento funcional é tipo Star Wars: 'Que a força esteja com você, mas sem machucar as costas.'",
		"🏋️‍♂️ 'Stairway to Heaven'? Não, é a escada infinita da academia e eu não vejo o céu, só o suor.",
		"🦵 Treino de pernas é como a Caverna do Dragão: você nunca acha a saída.",
		"🚴‍♂️ Subir no spinning é o meu 'Winter is coming.' Só que o inverno sou eu sofrendo.",
		"🦾 *Quando alguém rouba meu aparelho: 'Avengers... Assemble! No meu horário!.'",
		"🦵 Depois de um treino de perna, eu me sinto 'Um Jedi caído'. E o sabre? Minha toalha molhada.",
		"🏋️‍♀️ Treinar tríceps é como Friends: 'They don’t know that we know that they know!' Mas eu sei que dói.",
		"🦾 O levantamento terra não é 'Stranger Things', mas me manda direto pro mundo invertido.",
		"🏋️‍♂️ *Treino de bíceps: 'Vou fazer isso o dia todo.' - Capitão América enquanto segura o halter.",
		"💪 'Ninguém faz a menor ideia do peso que eu carrego... porque eu treino sozinho.' - Inspirado em Dark.",
		"🏋️‍♂️ 'Meu precioso! - Disse eu para o halter de 50kg no levantamento terra.' - Gollum mode on.",
		"🦵 *Treino de perna é tipo Matrix: 'There is no spoon, só dor.'",
		"💥 'Com grandes PRs vêm grandes responsabilidades.' - O mantra do Homem-Aranha na academia.",
		"🏃‍♂️ A esteira é como Jurassic Park: quanto mais rápido você corre, mais parece que algo tá te caçando.",
		"🦾 *Quando vejo alguém roubando meu banco no supino: 'Say my name!' - Walter White mode ativado.",
		"🏋️‍♀️ Agachamento é tipo 'O Poderoso Chefão': você sempre paga um preço no final.",
		"🥵 *Treinar no calor é como Mad Max: 'Fury Road' versão academia.",
		"🎬 Não sou ‘The Walking Dead’, mas meu corpo tá parecendo depois da terceira série de agachamento.",
		"📚 No fim do treino, só penso: ‘O Senhor dos Anéis’... porque, se eu aguentar mais um, é épico.",
		"🎸 ‘Stranger Things’ aconteceu quando descobri que o treino não tinha fim e a dor era outra dimensão.",
		"🔥 Comecei o dia com ‘O Poderoso Chefão’... agora eu sou o ‘Poderoso Supino’.",
		"🚀 O treino de peito foi tão pesado que me senti como se estivesse no ‘Interstellar’ tentando escapar da gravidade.",
		"🍿 No leg press, senti que estava dentro de ‘Jurassic Park’... as pernas quase pediram para sair correndo!",
		"💥 ‘Black Mirror’ na academia... cada vez que olho no espelho, vejo alguém diferente, mas sem músculo.",
		"🌪️ ‘O Homem do Castelo Alto’ deveria ser o título do meu treino de costas, tão alto e dolorido quanto.",
		"🏋️‍♀️ O treino de braço foi tão intenso que me senti um ‘Incrível Hulk’, mas sem a parte boa.",
		"📖 ‘O Pequeno Príncipe’ podia ser o nome do meu treino de abdômen... pequeno, mas cheio de lições.",
		"🦸‍♂️ Eu tentando completar as 3 séries: ‘Os Vingadores’ reunidos, mas ninguém me ajuda.",
		"🏆 Se eu tivesse mais força, me chamariam de ‘O Rei Leão’ da academia… mas hoje eu sou mais o Timão.",
		"🎤 ‘O Rei do Show’... eu quando consigo aumentar o peso no supino e todo mundo percebe.",
		"🦸‍♀️ Meus treinos de perna são tipo ‘Wonder Woman’... muita força, mas ninguém vê o esforço.",
		"📚 ‘O Hobbit’... porque minhas pernas, depois de um treino de agachamento, se tornaram pequenas montanhas.",
		"🎬 O treino de peito hoje foi uma verdadeira ‘Sessão da Tarde’... só que sem a parte divertida.",
		"💪 Entre um exercício e outro, só consigo pensar em ‘Breaking Bad’... meu corpo grita por uma dose de descanso.",
		"🚴‍♂️ Subir aquela esteira foi como ‘Vingadores: Guerra Infinita’... eu tentando alcançar o impossível.",
		"🌟 No final do treino, meu corpo é ‘Star Wars’... cheio de batalhas, mas sempre lutando pela galáxia do músculo.",
		"🏋️‍♀️ ‘Mundo Cão’ é o nome do treino de pernas... é assim que me sinto após a quarta série de agachamento.",
		"🎤 ‘Breaking Bad’ foi uma boa inspiração para o meu treino de tríceps... só que em vez de química, é dor pura.",
		"🍫 Como um ‘Chocolate’, meu treino de abdominal é doce no começo e amargo no fim.",
		"🎥 ‘O Grande Lebowski’ é o nome do meu treino de costas... jogado, mas com estilo.",
		"🚀 Depois de uma série de deadlift, me senti em ‘O Espaço Entre Nós’... com minhas costas distantes do chão.",
		"🔥 Minha série de agachamento foi um verdadeiro ‘Inferno’, só faltou a placa de fogo.",
		"🎬 Meu treino de ombro hoje foi tipo ‘O Ultimato’... não teve misericórdia!",
		"🍿 Fui até o fim com a ideia de ‘O Filme da Minha Vida’... mas no final, só vi dor e suor.",
		"🌍 ‘O Mundo Perdido’ é o que fica da minha energia depois de uma série de leg press.",
		"🌙 No final do treino, só penso: ‘De Volta Para o Futuro’... só assim eu me vejo indo embora dessa dor.",
		"💪 Treino de tríceps: 'I am vengeance.' - Batman, depois de trincar o braço no espelho.",
		"🦵 'Assim é como termina o mundo, não com um estrondo, mas com um treino de perna.' - Poeta e cansado.",
		"🚴‍♂️ 'Me chama de Flash, mas no spinning.' - Disse ninguém, enquanto pedala com 3 watts.",
		"💥 *Deadlift é tipo Transformers: 'Mais do que os olhos conseguem ver' no peso.",
		"🦾 'É perigoso ir sozinho, leve esta toalha!' - Zelda na academia, sempre prevenido.",
		"🏋️‍♂️ *Subir no rack de agachamento é tipo Interstellar: 'O tempo passa diferente lá dentro.'",
		"💪 Treino de costas? Chame de 'Breaking Bad': porque o trapézio não mente.",
		"🦵 *Treino de perna é como Stranger Things: você se sente no 'Upside Down' logo no segundo exercício.",
		"🥵 'Até que os ventos do Sahara soprem... ou que o ventilador da academia funcione.' - Inspirado em Aladdin.",
		"🏋️‍♀️ 'May the PRs be with you.' - Star Wars do agachamento.",
		"🦾 *Depois do cardio, é tipo Gladiador: 'Are you not entertained?' - Eu, suando igual Maximus.",
		"🏃‍♂️ A academia depois das festas é como The Walking Dead: só vejo zumbis no leg day.",
		"💪 'Eu posso fazer isso o dia todo.' - Capitão América, também conhecido como seu personal no supino.",
		"🏋️‍♂️ *Treino de ombro é tipo Titanic: você sente o 'Iceberg!' logo no meio da série.",
		"🦵 *Agachamento é o meu 'Círculo de Fogo': luto contra monstros... meus próprios limites!",
		"💥 'Eu sou o perigo.' - Walter White e eu, quando levanto 200kg no terra.",
		"🏃‍♂️ Corrida na esteira é como 'Gravidade': você se sente flutuando, mas é só o suor.",
		"🦾 'Say hello to my little friend.' - Eu e meu halter de 50kg, direto de Scarface.",
		"🥵 'I'm the king of the world!' - Eu, na última repetição de bíceps. Titanic vibes.",
		"🚴‍♂️ *Subir no spinning é tipo De Volta Para o Futuro: 'Onde estamos indo, não precisamos de descanso.'",
		"💪 'Avada Kedavra!' - O feitiço que uso na dor muscular pós-agachamento.",
		"🦵 *Treino de perna é como o Mundo de Avatar: 'Você descobre músculos que nem sabia que existiam.'",
		"💥 'Eu sou Groot.' - Meu mantra enquanto levanto peso no terra.",
		"🏋️‍♀️ *Treino de tríceps é tipo Game of Thrones: 'A dor está vindo.'",
		"🦾 'O que não me mata, me fortalece.' - Batman, enquanto malha o peitoral.",
		"🥵 *Depois de um treino intenso, é tipo 'Interestelar': um minuto no rack, sete anos no chuveiro.",
		"💪 *Treino de costas é como King Kong: 'Só os fortes sobrevivem.'",
		"🏃‍♂️ *Correr na esteira é como Missão Impossível: 'Não olhe para trás, ou você tropeça.'",
		"🦾 'Você levanta, ou morre tentando.' - Meu lema no supino, inspirado em 50 Cent.",
		"💥 *Treino de ombro é como Star Trek: 'Explorando novos limites.'",
		"🦵 'Hakuna Matata!' - Minha filosofia no leg day... até a terceira série.",
		"🏋️‍♂️ *Cada levantamento terra é tipo Jurassic Park: 'Você escuta ossos estalando no fundo.'",
		"💪 'É tudo sobre poder infinito!' - Thanos e eu no leg press.",
		"🚴‍♂️ *Treino de bike é como Forrest Gump: 'Eu só continuei pedalando.'",
		"🦵 *Agachamento é tipo Doctor Who: 'Sempre regenerando a força.'",
		"💥 *Treinar costas é como Os Incríveis: 'Mais trapézio, menos papo.'",
		"🏃‍♂️ 'Run, Forrest, run!' - Meu mantra no cardio de segunda-feira.",
		"🦾 *Levantar peso é tipo Toy Story: *'Há um halter no meu caminho!'",
		"💪 *Treino de bíceps é como O Grande Lebowski: 'Isso amarra tudo junto.'",
		"🥵 *Treino funcional é tipo Stranger Things: 'Você só quer sair do Upside Down.'",
		"🏋️‍♀️ *Cada série de supino é como Breaking Bad: *'Say my PR!'",
		"💥 *Deadlift é meu Matrix pessoal: 'Eu vejo o código... em cada repetição.'",
	},
	Yoga: {
		"🧘‍♀️ 'Hoje eu escolho acreditar em mim mesmo.' - Mas só depois de conseguir sair dessa pose impossível.",
		"🪷 'Inspire paz, expire gratidão.' - E uma boa dose de dor no alongamento.",
		"🧘‍♂️ 'Seja como a água, flua.' - Pena que eu sou mais como concreto: duro e imóvel.",
		"🕉️ 'A energia que você dá ao universo, você recebe de volta.' - Então, por que só volta câimbra?",
		"🧘 'Hoje eu abraço minha jornada.' - Mesmo que ela seja tropeçar no tapetinho.",
		"🪷 'Você é o mestre do seu destino.' - Exceto quando tenta o cachorro olhando para baixo.",
		"✨ 'Confie no processo.' - Eu confio, mas meu quadril não parece estar nessa vibe.",
		"🌱 'Agradeça ao seu corpo pelo que ele pode fazer.' - Ok, corpo, obrigada por reclamar em todas as poses.",
		"🧘‍♀️ 'Aquiete sua mente e ouça seu corpo.' - Ele está gritando: ‘Sai dessa posição!’",
		"🧘‍♂️ 'Encontre sua paz interior.' - Ela provavelmente está escondida no fundo do meu armário de biscoitos.",
		"✨ 'Seja presente no momento.' - Difícil, quando o momento envolve meu nariz grudado no joelho.",
		"🧘‍♀️ 'Respire fundo e solte o que não te serve.' - A gravidade certamente não está ajudando.",
		"🌿 'Cada dia é um novo começo.' - Exceto para minha flexibilidade, que parou nos anos 90.",
		"🌙 'Você é luz, você é amor.' - Mas hoje eu sou só dor nas costas.",
		"🧘‍♂️ 'Aceite o que é e deixe ir.' - Especialmente a ideia de parecer gracioso fazendo yoga.",
		"🌟 'Seu corpo é um templo.' - Um templo em reforma com andaimes caindo.",
		"🌼 'Onde o foco vai, a energia flui.' - Então, por que minha energia flui direto para a desistência?",
		"🧘 'Abra seu coração.' - E provavelmente uma costela, tentando essa torção.",
		"🪷 'Ame a si mesmo completamente.' - Inclusive as partes que odeiam a posição da árvore.",
		"🌺 'A dor é temporária.' - Mas o trauma de tentar aquela inversão vai durar para sempre.",
		"🧘‍♂️ 'Deixe ir o que não serve mais.' - Incluindo minhas expectativas sobre um alongamento decente.",
		"🌙 'Ouça sua respiração.' - Parece mais um motor engasgando, mas tudo bem.",
		"🌿 'Seja gentil consigo mesmo.' - Especialmente quando cair pela quinta vez.",
		"✨ 'Permita-se simplesmente ser.' - Contorcido e confuso na posição da cobra.",
		"🌟 'Tudo acontece por uma razão.' - Inclusive essa dor que eu não sabia que existia.",
		"🧘‍♂️ 'Mente quieta, coração aberto.' - Mas meu quadril está claramente revoltado.",
		"🌺 'Visualize seu melhor eu.' - Ele provavelmente está sentado no sofá, assistindo TV.",
		"🌼 'A paz começa dentro de você.' - E aparentemente termina assim que tento a pose do guerreiro.",
		"🪷 'Permita-se florescer.' - Mesmo que você pareça mais um cacto tentando yoga.",
		"🧘 'Seja como uma folha ao vento.' - Ou como um tronco quando eu caio.",
		"🌿 'A prática te leva à perfeição.' - Ou pelo menos ao ortopedista.",
		"🕉️ 'Aceite sua jornada única.' - Mesmo que ela envolva tropeçar no tapetinho.",
		"🧘‍♀️ 'Encontre sua força interior.' - Provavelmente escondida sob uma montanha de preguiça.",
		"✨ 'Tudo está conectado.' - Inclusive meu ego e a vergonha de cair na aula.",
		"🌙 'Escolha a calma.' - Difícil, quando o instrutor diz que isso era só o aquecimento.",
		"🌼 'Sinta-se grato pelo agora.' - Mesmo que o ‘agora’ envolva dor na lombar.",
		"🌟 'Você é um ser ilimitado.' - Exceto no alongamento, porque ali sou bem limitado.",
		"🧘‍♂️ 'Cada respiração é um renascimento.' - Pena que renasço cansado em todas.",
		"🌿 'O universo está em você.' - Certamente não na parte que entende essa pose invertida.",
		"🌺 'Celebre suas pequenas vitórias.' - Como sobreviver à aula sem ficar preso na pose do pombo.",
	},
	Walk: {
		"🚶‍♂️ *Minha caminhada é tipo Pica-Pau: 'Sorrindo por fora, mas pronto pra correr se o problema aparecer.'",
		"🏃‍♂️ *Caminhar é meu Tom e Jerry: 'Cada passo parece uma fuga de algo invisível.'",
		"🚶‍♀️ 'Caminho tanto que me sinto no Reino dos Cogumelos: só falta o Mario pra me salvar.'",
		"💪 *Caminhar no calor é meu Rick and Morty: 'Sempre em outra dimensão, longe do ar-condicionado.'",
		"🏞️ 'Pegue sua espada, Mestre dos Magos está perto!' - Pensamento recorrente nas subidas.",
		"🚶‍♂️ *Minha caminhada é Bob Esponja: 'Eu tentando parecer animado enquanto tudo que quero é parar.'",
		"💥 *Caminhar ao ar livre é tipo Meninas Super Poderosas: 'Lutando contra o cansaço, o crime... e o sol.'",
		"🚶‍♀️ *Cada passo na subida é Caverna do Dragão: 'O portal pra casa nunca aparece.'",
		"💪 'Vamos caminhar!' - Disse eu, acreditando ser uma Espiã Demais. Spoiler: não sou.",
		"🏃‍♂️ *Caminhar é meu Rick and Morty: 'Sempre acho que cheguei, mas a caminhada continua.'",
		"🚶‍♂️ 'Hora de aventura!' - Até perceber que a subida é longa e o fôlego é curto.",
		"💪 *Caminhar é tipo Tom e Jerry: 'Eu sou o Tom e a ladeira é o Jerry... sempre fugindo de mim.'",
		"🚶‍♀️ 'Preparem-se, amigos!' - Eu no início da caminhada, mas sem o Pikachu pra carregar meu peso.",
		"💥 *Caminhar no frio é tipo Scooby-Doo: 'Sempre correndo de algo imaginário.'",
		"🏃‍♂️ *Caminhar na areia é meu Bob Esponja: 'A cada passo, me sinto mais como o Patrick.'",
		"🚶‍♂️ 'Você não passa!' - Gandalf, ou a subida que enfrento toda semana.",
		"💪 *Cada ladeira é tipo Pica-Pau: 'Ela sobe, eu paro. Ela desiste? Nunca.'",
		"🚶‍♀️ *Minha caminhada é como Dragon Ball Z: 'Parece que nunca chega ao final.'",
		"💥 *Caminhar em círculos é meu Caverna do Dragão: 'Você nunca encontra a saída.'",
		"🚶‍♂️ 'Eu sou invencível!' - Até o primeiro morro acabar com meu ânimo.",
		"💪 *Minha caminhada é Scooby-Doo: *'Você resolve um mistério a cada passo: ‘Onde foi parar minha energia?’",
		"🚶‍♀️ *Caminhar ouvindo música é tipo Rick and Morty: 'Uma nova realidade com cada música que toca.'",
		"🏃‍♂️ 'Preparem-se para a próxima caminhada!' - Eu, tentando ser James do Team Rocket na subida.",
		"🚶‍♂️ *Caminhar é meu Hora de Aventura: 'Lutando contra o sono, as subidas e o cansaço.'",
		"💪 *Cada passo é tipo Tom e Jerry: 'Você está sempre tentando pegar algo, mas nunca alcança.'",
		"🚶‍♀️ *Caminhar na chuva é meu Bob Esponja: 'Só falta a música triste pra completar.'",
		"💥 *Cada subida é Pica-Pau: 'Uma risada debochada na minha cara enquanto eu sofro.'",
		"🏃‍♂️ *Caminhar rápido é como Dragon Ball Z: 'Tudo parece em câmera lenta enquanto o suor aumenta.'",
		"🚶‍♂️ 'Eu tenho o poder!' - Disse ninguém ao enfrentar o morro mais íngreme.",
		"💪 *Caminhar no parque é Scooby-Doo: 'Você vê sombra, mas jura que é um monstro.'",
		"🚶‍♀️ 'Essa ladeira é como o Mestre dos Magos: aparece do nada e te faz sofrer.'",
		"💥 *Caminhar com amigos é tipo Rick and Morty: 'Cada conversa é uma viagem interdimensional.'",
		"🚶‍♂️ 'Caminhar é um grande mistério.' - Scooby-Doo enquanto investiga meus passos lentos.",
		"💪 *Cada subida é Tom e Jerry: 'Você tenta vencer, mas só toma rasteira.'",
		"🚶‍♀️ *Caminhar é como Pokémon: 'Você só avança se tiver uma poção no bolso (garrafa d’água).'",
		"💥 *Caminhar com mochila é meu Bob Esponja: 'Carregando tudo, menos força.'",
		"🏃‍♂️ *Cada volta no parque é Rick and Morty: 'Parece infinito, mas é só o cansaço te enganando.'",
		"🚶‍♂️ *Caminhar ao sol é como Meninas Super Poderosas: 'Sofrendo, mas sempre estilosas.'",
		"💪 *Caminhada é tipo Dragon Ball Z: 'Só gritando você acredita que vai chegar.'",
		"🚶‍♀️ 'Continue andando!' - O Mestre dos Magos enquanto ignora meu pedido de descanso.",
		"🚶‍♂️ Caminhando na velocidade do Internet Explorer",
		"🚶‍♀️ Andando mais que Pokémon sem Pokébola",
	},
	VirtualRide: {
		"🚴‍♂️ Pedalando no metaverso da magreza",
		"🚴‍♂️ Pedalando em Nárnia virtual",
		"🚴‍♀️ Meu avatar pedala melhor que eu",
	},
	Crossfit: {
		"💪 WOD: Workout Of Destruição",
		"🏋️‍♂️ Crossfit é tipo Carrefour: tem de tudo",
		"💪 Box mais intenso que novela da Glória Perez",
		"🏋️‍♀️ Fazendo mais repetição que funk do verão",
	},
	MountainBikeRide: {
		"🚵‍♂️ Pedalando mais que o Louro José fugindo da Ana Maria",
		"🚵‍♀️ Trilha sonora da minha vida tem pedal e poeira",
		"🚵‍♂️ Aventura com dois aros e muita história",
		"🚵‍♀️ Pedalando onde o vento faz a curva",
	},
	Default: {
		"💪 Suando mais que político em CPI",
		"🎯 Malhação: Vibe Fitness",
		"💫 Treinando mais que participante do BBB",
		"🌟 Academia é meu Big Brother particular",
	},
}
